### ISSUE TITLE
Subir la Web Extension a AMO

### ISSUE THREAD

**Issue by MarionMoseby** [tasiomendez/mean-upm#1]
Hola! Lo primero, decirte que me encanta la extensión, está chulísima, mucho mejor que la otra más famosa, y, encima, open source! He estado [haciendo unas pruebis](https://www.extensiontest.com/test/c7a042f0-85f6-11eb-a15b-cf4ae008c843), y veo que, ahora que firefox ha adoptado la plataforma webextension, es compatible con firefox sin hacer cambios (menos la sección de estadísticas que no va, pero bueno), sólo haría falta subirlo a [addons.mozilla.org](addons.mozilla.org). ¿Te importaría hacerlo? Si prefieres que no, siempre puedo subirla yo, que la verdad es que estaría genial no tener que abrir chrome cada vez que me piden la media. 

También molaría a lo mejor que indiques más prominentemente en la descripción que es FOSS, es un valor diferenciador que la otra no tiene y que creo que es importante destacar :D

**Comment by tasiomendez** [comment]
Hola! Muchas gracias por el comentario. La extensión en principio es compatible con ambos navegadores (Chrome & Firefox), de forma que detecta el navegador en el que está instalada para que haya interoperabilidad. 

Ya intenté en su momento publicarla en AMO, ya que yo soy también usuario de Firefox. Sin embargo, no me la publicaron debido a que el público al que va dirigido es limitado y no es de uso general. Por esta razón, hay una [versión disponible desde el repositorio](https://github.com/tasiomendez/mean-upm/releases/latest/) que puede ser instalada directamente en Firefox, descargando el archivo `.xpi`. Esta versión tiene activadas las actualizaciones de forma que si detecta nuevas versiones publicadas, se actualizará desde el mismo automáticamente.

Si alguna función de la extensión no funciona, no dudes en abrir un issue para que pueda revisarlo o realizar un pull-request.
